version: "3.9"

services:
    webapp:
        container_name: sketch-it-webapp
        image: sketch-it-webapp
        build:
            context: .
            dockerfile: ./client/Dockerfile
            args:
                - NODE_ENV=production
        restart: always
        ports:
            - "8080:8080"
    server:
        container_name: sketch-it-server
        image: sketch-it-server
        build:
            context: .
            dockerfile: ./server/Dockerfile
            args:
                - NODE_ENV=production
        ports:
            - "7777:7777"

