name: Deploy client to Azure Static Web App

on:
  push:
    branches:
      - master
    paths:
      - client/**
      - common/**
  workflow_dispatch:

env:
  NODE_ENV: "production"
  SERVER_URL: ${{ secrets.SERVER_URL }}

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"
          output_location: "dist"
