name: Test and deploy

on:
  push:
    branches: [ master ]

jobs:
  test:
    uses: lukasz05/drawing-game/.github/workflows/test.yml@master

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

