name: Test

on:
  workflow_call:
  pull_request:
  push:
    branches-ignore: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
    
    - name: Check code style
      run: npm run prettier
    
    - name: Lint
      run: npm run lint
    
    - name: Run tests
      run: npm test
